language: java
jdk:
  - oraclejdk8
  - openjdk11

before_install:
  - chmod +x ./mvnw

install:
  - ./mvnw test-compile -DskipTests

script:
  - ./mvnw package jacoco:report

after_success:
  - ./mvnw coveralls:report
  - wget -c https://raw.githubusercontent.com/probonopd/uploadtool/9b4bea36eb9730a679d2eff05f7fb3fdca180ec9/upload.sh
  - bash upload.sh ./target/*-jar-with-dependencies.*

branches:
  except:
    - /^(?i:continuous)$/

notifications:
  email:
    on_success: never
    on_failure: change
