language: java
jdk:
  - oraclejdk8
  - openjdk11

before_install:
  - chmod +x ./mvnw

install:
  - ./mvnw test-compile -DskipTests

script:
  - ./mvnw test jacoco:report

after_success:
  - ./mvnw coveralls:report

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change
